### ISSUE TITLE
Will this project provide pre-trained models for evaluation?

### ISSUE THREAD

**Issue by detectRecog** [rehg-lab/dope_selfsup#2]
As defined in the config file 'configs/dope_ABC_CNN.yaml', the training process takes 3000 epochs. Authors also stated that "Contrastive training generally requires long training runs with multiple GPUs, which has potential for negative environmental impact. ". Actually, it will be very environmentally unfriendly for others to retrain this model for evaluation. 

Will this project provide pre-trained models for evaluation?

**Comment by sstojanov** [comment]
Thank you for your interest! You can download the best-validation checkpoints for models trained on ABC for all 5 splits using the following command
```
wget https://dl.dropbox.com/s/llb0osx1wcchcxc/ABC_modelnet_lowshot_ckpts.tar
```
